apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  labels:
    name: webapp-service
    app: app
spec:
  type: NodePort
  ports: 
    - port: 80
      targetPort: 80
      nodePort: 30008
  selector:
    app: app
    type: mvc 
