apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment
  labels:
    name: mssql-deployment
    app: app
spec:
    replicas: 1
    selector:
      matchLabels:
        app: app
        name: mssql-pod
    template:
        metadata: 
          name: mssql-pod
          labels:
              app: app
              name: mssql-pod
        spec:
          containers:
            - name: mssql
              image: mcr.microsoft.com/mssql/server
              ports:
                - containerPort: 1433
              env:
                - name: ACCEPT_EULA
                  value: "Y"
                - name: SA_PASSWORD
                  value: 1nCR3d1bl3*


