apiVersion: v1
kind: Service
metadata:
  name: mssql-service
  labels:
    name: mssql-service
    app: app
spec:
  type: NodePort
  ports: 
    - port: 1433
      targetPort: 1433
  selector:
    app: app
    name: mssql-pod
